1.引用的JS
<script>
//显示等待框
functionshowMask(){
$("#pageall#TEST").css('opacity','0.5');
$("#pageall#TEST").attr('class','panelactive');
$.afui.showMask('正在提交，请等待');
}
//取消等待
functionhideMask(){
$.afui.hideMask();
$("#pageall#TEST").attr('class','panel');
$("#pageall#TEST").css('opacity','1');
}
</script>
2.提交按钮
<buttonclass="btnbtn-primarybtn-block"onclick="showMask();doc
lick('1024-1');setTimeout(function(){hideMask()},1000);">提交
</button>
防止连续点击提交
showMask();doclick('1024-1');setTimeout(function(){hideMask()},1000);
showMask();//显示等待框
doclick('1024-1')//可以改为任意JS
setTimeout(function(){hideMask()},1000);//一秒后取消等待框
